# 端口
server:
  port: 8780
  servlet:
    context-path: /auth

# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/backend?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  # redis
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    timeout: 1000
    jedis:
      pool:
        max-wait: 1
        max-active: 20
        max-idle: 10
        min-idle: 0

# 输出SQL打印信息
logging:
  level:
    com.sprinboot.mybatisplus.mapper: debug

# mybatis

# mybatisPlus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

mybatis:
  type-aliases-package: com.dyz.authentication.entity
  configuration:
    map-underscore-to-camel-case: true
